CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255),
    email      VARCHAR(255),
    main_page  VARCHAR(8192),
    birth_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_authentication_details
(
    user_id BIGINT,
    password   VARCHAR(255),
    CONSTRAINT pk_user_authentication_details PRIMARY KEY (user_id),
    CONSTRAINT fk_users_user_authentication_details FOREIGN KEY (user_id) REFERENCES users (id)
);