CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255),
    email      VARCHAR(255),
    birth_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_authentication_details
(
    user_id    BIGINT,
    password   VARCHAR(255),
    CONSTRAINT pk_user_authentication_details PRIMARY KEY (user_id),
    CONSTRAINT fk_users_user_authentication_details FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS followers
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    follower_id     BIGINT,
    followed_id     BIGINT,
    created_date    TIMESTAMP WITHOUT TIME ZONE DEFAULT current_timestamp,
    CONSTRAINT pk_friends PRIMARY KEY (id),
    CONSTRAINT fk_followers_users_1 FOREIGN KEY (follower_id) REFERENCES users (id),
    CONSTRAINT fk_followed_users_2 FOREIGN KEY (followed_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS posts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_body   VARCHAR(8192),
    post_title  VARCHAR(256),
    owner_id    BIGINT,
    CONSTRAINT pk_posts PRIMARY KEY (id),
    CONSTRAINT fk_posts_users FOREIGN KEY (owner_id) REFERENCES users (id)
);