server:
  port: 8888
  servlet:
    context-path: "/app"

spring:
  application:
    name: restAPI
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/social_media
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: RS512
          issuer-uri: http://localhost:4000
          jwk-set-uri: http://localhost:4000/authentication/jwks
faas-url: http://localhost:8080/function/markdown
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5432/social_media