server:
  port: 9999
  servlet:
    context-path: "/authentication"
spring:
  application:
    name: authenticationServer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/social_media
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate

rabbit:
  email-exchange: EmailExchange
  email-routing-key: SEND_EMAIL
jwt:
  public:
    key: classpath:rsa.public.key
  private:
    key: classpath:rsa.private.key
  expiration: 86400000
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5432/social_media
  rabbitmq:
    host: email-rabbit